tasks:
  - name: setup
    before: |
      sudo apt update | tee -a ./.gitpod_logs/setup_before.log
      sudo apt install -y pciutils | tee -a ./.gitpod_logs/setup_before.log
      sleep 10
    init: |
      (curl -fsSL https://ollama.com/install.sh | sh) 2>&1 | tee -a ./.gitpod_logs/setup_init.log
      # Note: replacing with tinyllama does not reduce the response times, only the footprint.
      sleep 20
      ollama pull llama3.2 | tee -a ./.gitpod_logs/setup_init.log
      sleep 5
    command: |
      sleep 10
      ollama serve >> ./.gitpod_logs/ollama_stdout.log 2>>./.gitpod_logs/ollama_stderr.log &
      echo -e ""
      echo -e "\n\n\t\t** READY TO START... **\n\n"
      gp open gitpod_readme.md
